apiVersion: v1
kind: Service
metadata:
  name: demo-python
  namespace: demo
  labels:
    app: demo-python
spec:
  selector:
    app: demo-python
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
